CREATE TABLE "businesses" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"name" text NOT NULL,
	"phone" text,
	"address" text NOT NULL,
	"zipcode" text NOT NULL,
	"category" text NOT NULL,
	"description" text,
	"website" boolean DEFAULT false NOT NULL,
	"website_url" text,
	"rating" real,
	"review_count" integer,
	"google_maps_url" text,
	"keywords" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"summary" text,
	"insights" jsonb,
	"content_brief" jsonb,
	"generated_website_code" text,
	"outreach" jsonb,
	"github_url" text,
	"deployed_url" text,
	"lead_status" text DEFAULT 'new' NOT NULL,
	"priority" text DEFAULT 'low' NOT NULL,
	"priority_score" integer DEFAULT 0 NOT NULL,
	"notes" text,
	"last_contacted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "scrape_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"zipcode" text NOT NULL,
	"category" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone NOT NULL,
	"found" integer DEFAULT 0 NOT NULL,
	"saved" integer DEFAULT 0 NOT NULL,
	"skipped" integer DEFAULT 0 NOT NULL,
	"errors" integer DEFAULT 0 NOT NULL,
	"saved_list" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"skipped_list" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"error_list" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"found_names" jsonb DEFAULT '[]'::jsonb NOT NULL
);
